# Air config for dev live reload
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe serve --dev"
  cmd = "go build -o tmp/main.exe main.go"
  include_ext = ["go", "tpl", "html"]
  exclude_dir = ["static", "tmp", "vendor"]
  delay = 1000

[color] 
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true